"""
피험자 정보 및 실험 설정 (전체 Analysis 공용)
  - 모든 분석 과정에정 호출되어 사용됨

각 피험자 항목에 포함되는 필드(dict key-value pairs):
"yymmdd_NAMECODE" : {
        "SUB_number"         : (int) 피험자 번호 숫자만 (e.g. 1),
        "height"             : (int) 신장 (mm),
        "body_mass"          : (float) 체중 (kg),
        "sex"                : (str) 성별 ("M" / "F"),
        "age"                : (int) 만 나이,
        "protocol"           : (str) 프로토콜 이름 (e.g. "Symmetric" / "Asymmetric_Pilot" / "Asymmetric" ),
        "conditions"         : {"7kg_10bpm":  {"order":      (int) 프로토콜 순서 (1 ~ 4),
                                               "cycles":     (int) 반복 횟수,
                                               "error_log":  (str in list) 에러 로그 (e.g. []),
                                            },
                                "15kg_10bpm": {"order":      (int) 프로토콜 순서 (1 ~ 4),
                                              "cycles":      (int) 반복 횟수,
                                              "error_log":   (str in list) 에러 로그 (e.g. ["1AB", "4CA", "11AB"]),
                                            },
                                "7kg_16bpm":  {"order":      (int) 프로토콜 순서 (1 ~ 4),
                                               "cycles":     (int) 반복 횟수,
                                               "error_log":  (str in list) 에러 로그 (e.g. ["1AB", "7BC"]),
                                            }, 
                                "15kg_16bpm": {"order":      (int) 프로토콜 순서 (1 ~ 4),
                                               "cycles":     (int) 반복 횟수,
                                               "error_log":  (str in list) 에러 로그 (e.g. ["4CA", "1AB", "11AB"]),
                                            },
                            },
    },
"""

subjects = {
    
    "240124_PJH" : { #박준홍
        "SUB_number"         : 1,
        "height"             : 1740,
        "body_mass"          : 75.16,
        "sex"                : "M",
        "age"                : 30,
        "protocol"           : "Symmetric",
        "conditions"         : {"7kg_10bpm_trial1": {"order":       3,
                                                     "cycles":      11,
                                                     "error_log":   ['4'],
                                            },
                                "7kg_10bpm_trial2": {"order":       4,
                                                     "cycles":      12,
                                                     "error_log":   ['5','10'],
                                            },
                                "15kg_10bpm_trial1": {"order":      5,
                                                      "cycles":     11,
                                                      "error_log":  ['10'],
                                            },
                                "15kg_10bpm_trial2": {"order":      6,
                                                      "cycles":     10,
                                                      "error_log":  [],
                                            }, 
                                "7kg_16bpm_trial1": {"order":       1,
                                                     "cycles":      11,
                                                     "error_log":   ['1'],
                                            },
                                "7kg_16bpm_trial2": {"order":       2,
                                                     "cycles":      12,
                                                     "error_log":   ['5', '7'],
                                            },
                                "15kg_16bpm_trial1": {"order":      7,
                                                      "cycles":     10,
                                                      "error_log":  [],
                                            },
                                "15kg_16bpm_trial2": {"order":      8,
                                                      "cycles":     10,
                                                      "error_log":  [],
                                            },
                            },
    },
    
    "260306_KTY" : { #김태영
        "SUB_number"         : 1,
        "height"             : 1730,
        "body_mass"          : 66.74,
        "sex"                : "M",
        "age"                : 22,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     11,
                                               "error_log":  ['7AB'],
                                            },
                                "15kg_10bpm": {"order":      2,
                                              "cycles":      11,
                                              "error_log":   ['4CA'],
                                            },
                                "7kg_16bpm":  {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "15kg_16bpm": {"order":      3,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                            },
    },
    
    "260423_CES" : { #최은식 파일럿
        "SUB_number"         : 99,
        "height"             : 1700,
        "body_mass"          : 79.5,
        "sex"                : "M",
        "age"                : 30,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                            },
    },
    
   "260512_HSH" : { #함승훈
        "SUB_number"         : 98,
        "height"             : 1652,
        "body_mass"          : 75.82,
        "sex"                : "M",
        "age"                : 28,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     11,
                                               "error_log":  ['2AB','2CA'],
                                            },
                              #   "15kg_10bpm": {"order":      3,
                              #                 "cycles":      13,
                              #                 "error_log":   ['2AB', '7AB', '9CA'],
                              #               },
                              #   "7kg_16bpm":  {"order":      2,             # 5BC 다음부터 FP데이터 끊김. 
                              #                  "cycles":     12,
                              #                  "error_log":  ['3AB', '11AB'],
                              #               }, 
                              #   "15kg_16bpm": {"order":      4,
                              #                  "cycles":     10,
                              #                  "error_log":  [],
                              #               },
                            },
    },
   
   "260512_KCH" : { #강찬혁
        "SUB_number"         : 2,
        "height"             : 1680,
        "body_mass"          : 58.28,
        "sex"                : "M",
        "age"                : 27,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                                "15kg_10bpm": {"order":      3,
                                              "cycles":      11,
                                              "error_log":   ['8CA'],
                                            },
                                "7kg_16bpm":  {"order":      2,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "15kg_16bpm": {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                            },
    },
    
   "260519_SHY" : { # 신하연
        "SUB_number"         : 3,
        "height"             : 1702,
        "body_mass"          : 67.6,
        "sex"                : "F",
        "age"                : 28,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     11,
                                               "error_log":  ['2AB'],
                                            },
                                "10kg_10bpm": {"order":      2,
                                              "cycles":      13,
                                              "error_log":   ['7AB', '8AB', '8BC', '8CA', '12AB', '12CA'],
                                              # RWRB 마커 덜렁거려서 중간보수-> 이후에도 다시 떨어짐 (1바퀴 타이밍 맞춰서 다시 진행하긴 함).
                                            },
                                "7kg_16bpm":  {"order":      3,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "10kg_16bpm": {"order":      4,
                                               "cycles":     12,
                                               "error_log":  ['9CA', '10AB'],
                                            },
                            },
    },
    
   "260519_KMJ" : { # 김민지
        "SUB_number"         : 4,
        "height"             : 1582,
        "body_mass"          : 55.1,
        "sex"                : "F",
        "age"                : 23,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     14,
                                               "error_log":  ['1CA', '3AB', '9CA', '10AB'],
                                            },
                                "10kg_10bpm": {"order":      2,
                                              "cycles":      12,
                                              "error_log":   ['8AB'],
                                            },
                                "7kg_16bpm":  {"order":      3,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "10kg_16bpm": {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                            },
    },
    
   "260521_JSY" : { # 정성윤
        "SUB_number"         : 5,
        "height"             : 1542,
        "body_mass"          : 46.9,
        "sex"                : "F",
        "age"                : 25,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                                "10kg_10bpm": {"order":      2,
                                              "cycles":      11,
                                              "error_log":   ['4CA'],
                                            },
                                "7kg_16bpm":  {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "10kg_16bpm": {"order":      3,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                            },
    },
    
   "260521_KJA" : { # 강준아
        "SUB_number"         : 6,
        "height"             : 1633,
        "body_mass"          : 50.6,
        "sex"                : "F",
        "age"                : 23,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     11,
                                               "error_log":  ['5CA'],
                                            },
                                "10kg_10bpm": {"order":      2,
                                              "cycles":      11,
                                              "error_log":   ['8CA'],
                                            },
                                "7kg_16bpm":  {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "10kg_16bpm": {"order":      3,
                                               "cycles":     11,
                                               "error_log":  ['9AB'],
                                               # 처음 시작 늦게 함. tap detection의 offset 조정 필요.
                                            },
                            },
    },
    
   "260526_PJH" : { # 박재호
        "SUB_number"         : 7,
        "height"             : 1757,
        "body_mass"          : 71.8,
        "sex"                : "M",
        "age"                : 27,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     13,
                                               "error_log":  ['2CA', '4CA', '9AB'],
                                            },
                                "15kg_10bpm": {"order":      2,
                                              "cycles":      13,
                                              "error_log":   ['3AB', '9AB', '12CA'], # 4AB도 부딪혔는지 확인 필요.
                                            },
                                "7kg_16bpm":  {"order":      3,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "15kg_16bpm": {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                            },
    },
    
   "260526_PJM" : { # 박지명
        "SUB_number"         : 8,
        "height"             : 1796,
        "body_mass"          : 93.8,
        "sex"                : "M",
        "age"                : 29,
        "protocol"           : "Asymmetric",
        "conditions"         : {"7kg_10bpm":  {"order":      1,
                                               "cycles":     10,
                                               "error_log":  [],
                                            },
                                "15kg_10bpm": {"order":      2,
                                              "cycles":      11,
                                              "error_log":   ['9AB'],
                                            },
                                "7kg_16bpm":  {"order":      4,
                                               "cycles":     10,
                                               "error_log":  [],
                                            }, 
                                "15kg_16bpm": {"order":      3,
                                               "cycles":     12,
                                               "error_log":  ['11AB'],
                                               # 중간에 추가로 걸린 거 같아서 혹시 몰라 1회 더 함.
                                            },
                            },
    },
    
    
    
    
    
    
}